### ISSUE TITLE
A few weird methods are exposed to the page objects in tests

### ISSUE THREAD

**Issue by nadvolod** [titusfortner/sauce_junit#2]
I noticed that the framework exposes some methods that I believe should not be visible to the tests.
https://www.evernote.com/l/AWQsmBTdZXJBZbaGAnxfBtInQgeXG_d_5dU

**Comment by titusfortner** [comment]
Yeah, I think you are right. The methods will all need a private/protected pass and maybe some final thrown in there on things? At any rate, I updated these in the framework, so next release it'll be fixed here.
